modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/teamfusion/Summoner-Scrolls/issues"
license = "MIT (Code); ARR (Assets)"

[[mods]]
modId = "summoner_scrolls"
version = "${version}"
displayName = "Summoner Scrolls"
authors = "Team Fusion"
description = '''
Amongus Desc!
'''
logoFile = "logo.png"

[[dependencies.summoner_scrolls]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.summoner_scrolls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.summoner_scrolls]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"